"use client";

import type { MerchantMember, MerchantOutlet } from "@tuma/shared";
import { LogOut, ShieldCheck, UserPlus } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { api, errorMessage } from "../../lib/api";
import { useAuth } from "../../lib/auth-context";

export default function AccountPage() {
  const { user, merchant, merchants, selectMerchant, refreshMerchants, logout } = useAuth();
  const [members, setMembers] = useState<MerchantMember[]>([]);
  const [outlets, setOutlets] = useState<MerchantOutlet[]>([]);
  const [registrationNumber, setRegistrationNumber] = useState(merchant?.registration_number ?? "");
  const [taxId, setTaxId] = useState(merchant?.tax_id ?? "");
  const [identifier, setIdentifier] = useState("");
  const [role, setRole] = useState<"finance" | "manager" | "cashier">("cashier");
  const [outletId, setOutletId] = useState("");
  const [ownerIdDocument, setOwnerIdDocument] = useState<File | null>(null);
  const [businessDocument, setBusinessDocument] = useState<File | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  const load = useCallback(async () => { if (!merchant) return; if (merchant.member_role === "cashier") { setOutlets((await api.merchantOutlets(merchant.id)).outlets); setMembers([]); return; } const [m, o] = await Promise.all([api.merchantMembers(merchant.id), api.merchantOutlets(merchant.id)]); setMembers(m.members); setOutlets(o.outlets); }, [merchant]);
  useEffect(() => { setRegistrationNumber(merchant?.registration_number ?? ""); setTaxId(merchant?.tax_id ?? ""); load().catch((cause) => setError(errorMessage(cause))); }, [load, merchant]);

  async function submitKyc(event: React.FormEvent) { event.preventDefault(); if (!merchant) return; if (!merchant.has_owner_id_document && !ownerIdDocument) { setError("Upload the business owner's National ID."); return; } if (!merchant.has_business_document && !businessDocument) { setError("Upload the business registration document."); return; } setBusy(true); setError(""); try { await api.submitMerchantKyc(merchant.id, { registrationNumber, taxId }); if (ownerIdDocument) await api.uploadMerchantKycDocument(merchant.id, "owner-id", ownerIdDocument); if (businessDocument) await api.uploadMerchantKycDocument(merchant.id, "business-registration", businessDocument); setOwnerIdDocument(null); setBusinessDocument(null); await refreshMerchants(); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  async function addMember(event: React.FormEvent) { event.preventDefault(); if (!merchant) return; setBusy(true); setError(""); try { await api.addMerchantMember(merchant.id, { identifier, role, outletId: outletId || null }); setIdentifier(""); await load(); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  async function remove(userId: string) { if (!merchant) return; setBusy(true); try { await api.removeMerchantMember(merchant.id, userId); await load(); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }

  if (!merchant) return null;
  return <div className="space-y-5 px-4 py-5"><header><h1 className="text-2xl font-black">Business account</h1><p className="text-sm text-ink-500">{user?.name} · {merchant.member_role}</p></header>
    {error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {merchants.length > 1 && <section className="home-card space-y-2"><label className="text-xs font-bold text-ink-500">Current business</label><select value={merchant.id} onChange={(e) => selectMerchant(e.target.value)} className="min-h-12 w-full rounded-xl border border-[var(--border-faint)] px-3">{merchants.map((m) => <option key={m.id} value={m.id}>{m.display_name}</option>)}</select></section>}
    {merchant.member_role !== "cashier" && <section className="home-card space-y-3"><div className="flex items-start gap-3"><ShieldCheck className="h-5 w-5 text-gold"/><div><h2 className="font-bold">Business verification</h2><p className="text-xs text-ink-500">Status: {merchant.kyc_status?.replaceAll("_", " ") ?? "pending"}. Documents are private and available only to authorized Tuma reviewers.</p></div></div><form onSubmit={submitKyc} className="space-y-2"><input required value={registrationNumber} onChange={(e) => setRegistrationNumber(e.target.value)} placeholder="URSB registration number" className="min-h-12 w-full rounded-xl border border-[var(--border-faint)] px-3"/><input required value={taxId} onChange={(e) => setTaxId(e.target.value)} placeholder="URA TIN / tax identifier" className="min-h-12 w-full rounded-xl border border-[var(--border-faint)] px-3"/><label className="block rounded-xl border border-[var(--border-faint)] p-3 text-xs"><span className="mb-2 block font-bold">Owner National ID {merchant.has_owner_id_document ? "✓ uploaded" : ""}</span><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(e) => setOwnerIdDocument(e.target.files?.[0] ?? null)}/></label><label className="block rounded-xl border border-[var(--border-faint)] p-3 text-xs"><span className="mb-2 block font-bold">Business registration document {merchant.has_business_document ? "✓ uploaded" : ""}</span><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(e) => setBusinessDocument(e.target.files?.[0] ?? null)}/></label><label className="flex gap-2 text-xs text-ink-500"><input required type="checkbox"/>I declare that these business details and documents are accurate and authorized.</label><button disabled={busy} className="min-h-11 w-full rounded-full bg-gold font-bold text-ink-gold disabled:opacity-50">{busy ? "Uploading securely…" : "Submit for verification"}</button></form></section>}
    {merchant.member_role !== "cashier" && <section className="home-card space-y-3"><div className="flex gap-3"><UserPlus className="h-5 w-5 text-gold"/><div><h2 className="font-bold">Team access</h2><p className="text-xs text-ink-500">Cashiers confirm sales; finance can settle; managers operate outlets. Only owners manage staff.</p></div></div>{members.map((member) => <div key={member.user_id} className="flex justify-between gap-3 border-t border-[var(--border-faint)] pt-3 text-sm"><span><span className="block font-semibold">{member.name}</span><span className="text-xs text-ink-500">{member.role} · {member.status}</span></span>{merchant.member_role === "owner" && member.role !== "owner" && member.status === "active" && <button disabled={busy} onClick={() => remove(member.user_id)} className="text-xs font-bold text-red-600">Remove</button>}</div>)}{merchant.member_role === "owner" && <form onSubmit={addMember} className="space-y-2 border-t border-[var(--border-faint)] pt-3"><input required value={identifier} onChange={(e) => setIdentifier(e.target.value)} placeholder="Staff email or phone" className="min-h-11 w-full rounded-xl border border-[var(--border-faint)] px-3"/><div className="grid grid-cols-2 gap-2"><select value={role} onChange={(e) => setRole(e.target.value as typeof role)} className="min-h-11 rounded-xl border border-[var(--border-faint)] px-3"><option value="cashier">Cashier</option><option value="manager">Manager</option><option value="finance">Finance</option></select><select value={outletId} onChange={(e) => setOutletId(e.target.value)} className="min-h-11 rounded-xl border border-[var(--border-faint)] px-3"><option value="">All outlets</option>{outlets.map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</select></div><button disabled={busy} className="min-h-11 w-full rounded-full border border-gold font-bold text-gold">Add existing Tuma user</button></form>}</section>}
    <button onClick={logout} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-full border border-red-300 font-bold text-red-600"><LogOut className="h-4 w-4"/>Log out</button>
  </div>;
}
